// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd-uu-cmyw8a1ig_bRBUkn0pyxmS68C2k',
    appId: '1:800621873570:web:49a598b6768267d283cafb',
    messagingSenderId: '800621873570',
    projectId: 'firenote-2c25a',
    authDomain: 'firenote-2c25a.firebaseapp.com',
    storageBucket: 'firenote-2c25a.firebasestorage.app',
    measurementId: 'G-6SR06MQ0CP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIyDkm4dUPHaZGXcIi0k3-Lnx1Je3Hq1A',
    appId: '1:800621873570:android:1c406d4b883f44e083cafb',
    messagingSenderId: '800621873570',
    projectId: 'firenote-2c25a',
    storageBucket: 'firenote-2c25a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhKudmQSwOQ_xH7SDjSiDP1gGpFmwvdJU',
    appId: '1:800621873570:ios:5d452260a7ea41ba83cafb',
    messagingSenderId: '800621873570',
    projectId: 'firenote-2c25a',
    storageBucket: 'firenote-2c25a.firebasestorage.app',
    iosBundleId: 'com.example.fireNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhKudmQSwOQ_xH7SDjSiDP1gGpFmwvdJU',
    appId: '1:800621873570:ios:5d452260a7ea41ba83cafb',
    messagingSenderId: '800621873570',
    projectId: 'firenote-2c25a',
    storageBucket: 'firenote-2c25a.firebasestorage.app',
    iosBundleId: 'com.example.fireNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd-uu-cmyw8a1ig_bRBUkn0pyxmS68C2k',
    appId: '1:800621873570:web:878abe6f3da0cae583cafb',
    messagingSenderId: '800621873570',
    projectId: 'firenote-2c25a',
    authDomain: 'firenote-2c25a.firebaseapp.com',
    storageBucket: 'firenote-2c25a.firebasestorage.app',
    measurementId: 'G-SML048N79R',
  );
}
